example_segmentation.py

Hi, i think you can even improve the example by using the `function_call` argument to force the model using the provided functions/schema - see [documentation](https://platform.openai.com/docs/api-reference/chat/create#chat/create-function_call) and an example here: [Forcing the use of specific functions or no function](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_call_functions_with_chat_models.ipynb) .
Works as expected and uses 15 tokens less in this short example ;-) .

use function call argument to force function call

---

question_answer_subquery.py

- **Solution:** Implement flat tasks with indices and dependencies that reference the indices instead of using recursion.
- **Risks:** Possibility of hallucinations. of indicies (but cot could make that a bit better)
- **Solution:** Use two calls instead of one. The first call is for planning with CoT (Context of Task), and the second call is to translate the plan into a schema. 
- **Thoughts:** its not needed, can work with one on simple problems, Although less impressive, this solution works well. It can leverage GPT-4 for planning and GPT-3.5 for translation. Alternatively, using only GPT-4 in a single call is possible, but it often tries to be overly smart and ends up breaking the schema. 
- The idea of using flat tasks with indices originated from GPT-4 breaking my schema which lead …

Query planner prototype

---

README.md
safe_sql.py

The SQL class is designed to represent a single SQL query and its parameters, as well as assess the security risk associated with the query. The user-provided input is examined for potential SQL injection attempts or abusive queries, marking these as dangerous when identified. When it comes to generating SQL queries, this script always leans on using query parameters for user-defined inputs, adhering to best security practices.
The function create_query() calls upon OpenAI's GPT-3.5 Turbo model to construct SQL queries from given user requests. It provides the AI model with context and instruction via the ChatCompletion.create() method, outlining its role as a SQL agent, and requiring it to identify and mark any dangerous queries.
In the main function, a list of test queries is processed. …

Generating safe SQL 

---

openai_function_call.py

Don't want to bother you ;-) - but as I use the `OpenAISchema` quite a lot maybe you can also make use of these small improvements.
This looks a bit hacky (feel free to edit, I didn't find a better solution to edit the pydantic json schema output) but makes the function signatures a lot cleaner - in my tests this made function calls more reliable (as it is closer to the finetuned function signatures - see e.g. [here](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_call_functions_for_knowledge_retrieval.ipynb) for reference) and uses less tokens:
```python
@openai_function
def test(a:int=1, b:str="a"):
"""test"""
pass
print(test.openai_schema)
print()
class Test(OpenAISchema):
"""test"""
a:int=1
b:str="a"
print(Test.openai_schema)
```
on main:
```
{'description': …
```

slimmer openai function signature

---

README.md

adds a warning to ensure python v > 3.9, 
correct name of pip package as per PyPI.

warning for v > 3.9, correct package name.

---

openai_function_call/function_calls.py

When getting longform answers from OpenAI that contains newlines or tabs, the string returned doesn't have escaped control characters.
`strict=False` allows parsing of these strings with control characters, with character codes in the 0-31 range, including '\t' (tab), '\n', '\r' and '\0'."

Allow less strict JSON parsing

---

openai_function_call/function_calls.py

This pull request addresses issue #41 "Exclude properties with defaults from required." 
- Modified the code to exclude properties with defined default values from the `required` field in the parameters dictionary
- This change provides more flexibility when dealing with properties that have default values
- By setting this default to "None" this allows us to use optional data

Excluding properties with defaults from required as per issue #41

---

examples/query_planner_execution/query_planner_execution.py
instructor/function_calls.py

Goal: Enhancing compatibility with API frameworks
Changes: Updates the way we assign the `message` variable in our code. Instead of using `completion.choices[0].message`, we now use `completion['choices'][0]['message']`. This change not only maintains the current functionality but also enhances the module's compatibility with API frameworks like FastAPI, allowing users to conform to a JSON response more easily.
P.S. @jxnl Huge fan of the repo and work that has been done!

update message assignment

---

docs/maybe.md
docs/tips/index.md
examples/simple-extraction/maybe_user.py
examples/simple-extraction/user.py
instructor/__init__.py
instructor/dsl/__init__.py
instructor/dsl/maybe.py
mkdocs.yml
pyproject.toml

You can create a wrapper class to hold either the result of an operation or an error message. This allows you to remain within a function call even if an error occurs, facilitating better error handling without breaking the code flow.
```python
class UserDetail(BaseModel):
age: int
name: str
role: Optional[str] = Field(default=None)
class MaybeUser(BaseModel):
result: Optional[UserDetail] = Field(default=None)
error: bool = Field(default=False)
message: Optional[str]
def __bool__(self):
return self.result is not None
```
With the `MaybeUser` class, you can either receive a `UserDetail` object in result or get an error message in message.
You can further simplify this using instructor to create the `Maybe` pattern.
```python
import instructor
MaybeUser = instructor.Maybe(UserDetail)
``` …

Maybe helper to dynamically create a class with errors on extraction

---

.github/workflows/mkdocs.yml

This PR addresses an issue where the MkDocs CI Pipeline would fail during the installation of `mkdocs-material-insiders` due to missing credentials. It potentially resolves issue #49.
- Ensure credentials are passed during the `Install Requirements` step by utilizing the `GH_TOKEN` environment variable.
- Leverage the value stored in `secrets.GH_TOKEN` to set the `GH_TOKEN` environment variable.
To successfully implement this fix, the following setup is necessary:
1. The repository must have an [actions repository secret](https://github.com/jxnl/instructor/settings/secrets/actions) labeled as `GH_TOKEN`.
2. This `GH_TOKEN` secret should correspond to a [GitHub token](https://github.com/settings/tokens/new) with a minimum access level of the `repo` scope.

Fix MkDocs Build in CI Pipeline

---

requirements-doc.txt

This PR resolves the MkDocs CI Pipeline failure caused by the absence of the `mkdocs-minify-plugin`, which is specified in the `mkdocs.yaml` configuration.
Following the resolution of authentication problems in #108, this update ensures the entire workflow will finish successfully.
- Add `mkdocs-minify-plugin` to `requirements-doc.txt`.

Add minify plugin to requirements-doc.txt

---

.github/workflows/mkdocs.yml

The third time's the charm (hopefully). Following the recommendation from [the optimize documentation](https://squidfunk.github.io/mkdocs-material/plugins/optimize/#configuration), this PR ensures `pngquant` is installed prior to building the `instructor` documentation. 
I apologize for the iterative approach. Because I have no access to MkDocs insiders, I couldn't replicate `instructor`'s precise workflow to test it comprehensively in one go.
- Install `pngquant` before building `instructor`'s documentation.
Tested the installation of `pngquant` in [this fork](https://github.com/jlondonobo/instructor/actions/runs/6286240333/job/17069475980).

Install `pngquant` in MkDocs Pipeline for correct image optimization

---

instructor/patch.py

Really simple PR. `client.chat.completions.create` was typed out twice in the doc string for the `patch` function. 
This initially threw me off thinking the patch was for both async and normal client.

small typo fix

---

docs/examples/extracting_tables.md
docs/examples/index.md
examples/vision/run_table.py
mkdocs.yml

This is a peculiar example, and I'm unsure how to work with types in this context.
Here's the code I have:
```python
class Table(BaseModel):
caption: str = Field(
description="The caption of the table, which should provide a detailed description"
)
table_md: str = Field(description="The markdown representation of the table")
def df(self):
return (
pd.read_csv(
StringIO(self.table_md),  # Remove whitespaces
sep="|",
index_col=1,
)
.dropna(axis=1, how="all")
.iloc[1:]
)
```
When I use the OpenAI vision model to extract tables from a given URL:
```python
url = "https://a.storyblok.com/f/47007/2400x2000/bf383abc3c/231031_uk-ireland-in-three-charts_table_v01_b.png"
tables = extract_table(url)
for tbl in tables:
print(tbl.caption)
print(tbl.table_md)
print(tbl.df())
```
The table displays the …

example: Table extraction w/ Pydantic

---

ellipsis.yaml

Adds an `ellipsis.yaml` file, which enables [Ellipsis](www.ellipsis.dev) to automatically review pull requests as they're opened.
- See https://docs.ellipsis.dev for the full reference of the config file

add ellipsis.yaml config file;

---

docs/examples/index.md

From #293, I forgot to update examples/index.md to include the new tutorial. This PR fixes that.

[docs] Add example link on index page

---

docs/concepts/raw_response.md
instructor/patch.py
tests/openai/test_patch.py
tests/test_function_calls.py

This pull request aims to solve Issue #341, by introducing a new variable named `total_usage` of type `openai.types.completion_usage.CompletionUsage`, which accumulates the token usage from all previous responses, including those that failed validation or JSON decoding, allowing better cost management. 
Currently it does not return the total usage if `max_retries` is reached, since instructor just raise an exception when it happens. It would be worthwhile to consider enhancing the functionality to ensure that `total_usage` is reported even when `max_retries` is exceeded, to provide a complete picture of token usage for monitoring and optimization purposes.

Introduce `total_usage` variable to track cumulative token usage

---

instructor/patch.py
pyproject.toml
tests/openai/test_multitask.py

fix: Adding tests to make sure non-stream iterables work

---

docs/tutorials/4-validation.ipynb

`client` is a required argument for `llm_validator`. Fixed the incorrect `openai_client` argument and, in a second instance, the missing `client` argument.

Fixed incorrect/missing arguments

---

docs/tutorials/2-tips.ipynb

Typo fix and rephrasing suggestion for section "Defining Relationships" in the Tips and Tricks section of the Tutorials. 
https://useinstructor.com/tutorials/2-tips/#defining-relationships

typo fix and rephrasing suggestion

---

instructor/retry.py

Retries did not work for Cohere client because it was not appending the right `kwargs` value for Cohere chat history and the validation error message to be appended had the wrong object definition.
Related to but not directly: https://github.com/jxnl/instructor/issues/584

Fixed Cohere retries

---

docs/index.md

This PR suggests a fix heading levels for getting started section. They were inconsistent across sub-sections.
It's a small fix but I noticed the inconsistency when I was reading the docs. Hope you appreciate it
**Before:**
(note how `Using Gemini` is at the same level as `Getting Started`)
**After:**

Fix heading indentation in the getting started section of the docs

---

docs/cli/usage.md

Usage tracking list command is missing a '-' in its -n flag. Listing the available options with 'instructor usage list --help' will hint the correct flag is '--n' instead of '-n'

Update usage.md 'constructor usage list' command documentation

---

docs/blog/posts/migrating-to-uv.md

Adding new article that walks through issues we faced when migrating to `uv`

feat: add new article on migrating to uv

---

.cursor/rules/new-features-planning.mdc

This PR updates the GitHub cursor rules to improve the development workflow.
- Updated Cursor attribution to use proper https URL format (`https://cursor.com` instead of `mdc:cursor.com`)
- Added detailed instructions for conventional commit formats (type, scope, description)
- Added guidance for multiline commit messages
- Included templates and examples for creating PRs with multiline bodies using:
- The heredoc approach (`cat <<EOF`)
- File-based approach (`-F` flag)
- Added reminder to clean up temporary files after PR creation
Verified the updated format works correctly by creating a test PR.
This PR was written by [Cursor](https://cursor.com)

docs(github): update cursor rules with proper website link and multiline PR instructions
