567-labs/instructor

- openai_function_call/__init__.py
- openai_function_call/function_calls.py
- requirements.txt
- tests/test_function_calls.py
Fixes #17 
Added `openai_schema` decorator that inherits from BaseModel
```python3
@openai_schema
class MyClass(BaseModel):
...
```
> Added openai_schema decorator

- mkdocs.yml
- requirements-doc.txt
Reverts jxnl/openai_function_call#46
> Revert "Social Images"

- README.md
- as s import wasn't working for me
- import pprint
> typo readme DSL example

- docs/index.md
- docs/philosophy.md
Fixed some typos and removed a phrase in Section 1 in index which seemed to be contrary to Section 2
> fixed docstring typos

- docs/examples/planning-tasks.md
- examples/query_planner_execution/query_planner_execution.py
> Fix typo dependancy -> dependency

- docs/blog/posts/rag-and-beyond.md
This PR simply makes a few minor grammatical edits.
> Minor edits

- instructor/__init__.py
Seems like `unpatch()` was missing in the public namespace. So, I just added that.
> Expose unpatch() function

- tutorials/1.introduction.ipynb
Worked through introduction.ipynb
great quote at the end " With instructor the goal is to be as light weight as possible, get you as close as possible to the openai api, and then get out of your way. "
Thanks, Jason.
👍
> Tutorials creative acts in documentation

- instructor/function_calls.py
- instructor/patch.py
> Revert "Add new Mode for Anyscale's json schema schema type "

- docs/examples/knowledge_graph.md
- examples/knowledge-graph/run_stream.py
Added in a new section for Instructor which uses the code in `run_stream.py` to iteratively generate and update a knowledge graph.
> Updated the Knowledge Graph article

- docs/concepts/fields.md
Add missing comma in `chain_of_thought` property in `DateRange` class in "Exclude" example.
> Update fields.md - fix typo, missing comma

- instructor/function_calls.py
Deprecated FUNCTIONS and used TOOLS as default.
> Update function call mode and add deprecation warning

- examples/batch-classification/run-cache.py
Adding a new example to showcase how to use a cache when dealing with async functions
> Adding support for caching async functions

- docs/blog/posts/caching.md
- docs/blog/posts/learn-async.md
- docs/blog/posts/rag-and-beyond.md
- docs/blog/posts/validation-part1.md
- docs/examples/planning-tasks.md
- tutorials/3.0.applications-rag.ipynb
> fix a few spelling mistakes & typos

- tutorials/1.introduction.ipynb
I saw some small duplication of wording and removed it.
> Update the readme and remove some wording duplication.

- examples/ollama/README.md
- examples/ollama/run.py
- instructor/patch.py
first time trying to contribute, wasn't sure if this is what you were looking for an example with ollama.
https://github.com/jxnl/instructor/assets/98295827/429da794-c8fc-4837-87ae-5e685aadfde5
> Add ollama run.py with completion functionality

- instructor/patch.py
> Be robust to null values while updating token counts

- instructor/patch.py
seems like a typo that should be fixed.
> Fixes prompt typo

- .github/workflows/mypy.yml
- instructor/cli/files.py
- instructor/cli/usage.py
- instructor/exceptions.py
This PR adds types to the following files, as per https://github.com/jxnl/instructor/issues/390.
```
instructor/cli/files.py
instructor/cli/usage.py
instructor/exceptions.py
```
> Include types to most upstream modules

- docs/examples/image_to_ad_copy.md
> fix: Fixed links in image to add copy 

- .github/workflows/test.yml
- docs/concepts/patching.md
- docs/concepts/retrying.md
- docs/concepts/usage.md
- docs/index.md
- tests/dsl/test_partial.py
- tests/llm/test_openai/test_patch.py
- tests/llm/test_openai/test_retries.py
- tests/llm/test_openai/test_stream.py
The current pipeline has a bunch of failing tests due to doc test imports/formatting, some tests which haven't been updated for a while and a vertexai key that isn't confitued.
This fixes a bunch of different tests and gives a nice green pipeline.
> Fix Pipeline Failing Tests
